/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lh_updateapk_utils_PatchUtils */

#ifndef _Included_com_lh_updateapk_utils_PatchUtils
#define _Included_com_lh_updateapk_utils_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lh_updateapk_utils_PatchUtils
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lh_updateapk_utils_PatchUtils_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
